---
# tasks file for ansible-role-nrpe
- name: Include vars of stuff.yaml into the 'defaults' variable (2.2).
  include_vars:
    file: ../defaults/main.yml
    name: main

# GPG check is disabled because opsview are not signing their packages.
- name: Import EPEL GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state=present


- name: Check for EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present
    
- name: Install opsview-agent package
  yum: name=http://downloads.opsview.com/opsview-core/latest/yum/centos/7/x86_64/opsview-agent-4.6.0.436-1.ct7.x86_64.rpm
    state=present
  notify:
    - "restart opsview-agent"
    
- name: Install Common Plugins
  yum: name={{ item }} state=latest update_cache=true 
  loop: [libmcrypt, glibc.i686, ksh, libsemanage-python]
  
- name: copy custom plugin files
  copy: src=../templates/{{ item }} dest={{ opsview_libexec_dir }} mode=0755

  with_items:
    - check_diskstat.sh
    - check_raid.pl
    - check_memory
    - check_htblacklist.sh

- name: Remove all hardcoded command settings from default nrpe.cfg
  lineinfile:
    state: absent
    regexp: '^command\['
    path: '/usr/local/nagios/etc/nrpe.cfg'
  notify:
    - "restart opsview-agent"
  when: remove_hardcoded_checks|default(false)|bool

- name: Template in override config file (to set allowed_hosts)
  template: src=../templates/override.cfg.j3 dest={{ opsview_cfg_file }} mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  notify:
    - "restart opsview-agent"

- name: Template in custom checks config file for opsview
  template: src=../templates/check_opsview.cfg.j2
            dest={{ opsview_include_dir }}/{{ nagios_custom_checks_file }}
            mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
 
  
- name: Make sure opsview-agent is started and enabled
  service: name=opsview-agent state=restarted enabled=yes
